# Generated by Django 5.1.3 on 2024-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='en', max_length=2, verbose_name='язык пользователя'),
        ),
    ]
